require("user.core.options")
require("user.core.keymaps")
require("user.plugins-setup")
require("user.plugins.nvim-tree")
require("user.plugins.tokyonight")
require("user.core.colorscheme")
require("user.plugins.telescope")
--require("user.plugins.lsp")
require("user.lsp.init")
require("user.plugins.cmp")
require("user.plugins.treesitter")
require("user.plugins.comment")
require("user.plugins.bufferline")


